@list = ["The Beatles",
"Bob Dylan",
"The Rolling Stones",
"David Bowie",
"Bruce Springsteen",
"Radiohead",
"Neil Young",
"Elvis Presley",
"The Beach Boys",
"Prince",
"R.E.M.",
"Led Zeppelin",
"U2",
"The Who",
"The Velvet Underground",
"The Clash",
"Jimi Hendrix",
"Marvin Gaye",
"Elvis Costello",
"Nirvana",
"Kanye West",
"Pink Floyd",
"The Smiths",
"Bob Marley and The Wailers",
"Miles Davis",
"Stevie Wonder",
"Madonna",
"Van Morrison",
"Talking Heads",
"James Brown",
"Michael Jackson",
"Aretha Franklin",
"Arcade Fire",
"The Cure",
"Tom Waits",
"Nick Cave The Bad Seeds",
"The Kinks",
"Blur",
"The Byrds",
"Public Enemy",
"Jay-Z",
"The Doors",
"Pixies",
"Beastie Boys",
"John Lennon",
"Chuck Berry",
"Beck",
"Lou Reed",
"New Order",
"PJ Harvey",
"Kraftwerk",
"Johnny Cash",
"Oasis",
"Creedence Clearwater Revival",
"Joy Division",
"John Coltrane",
"LCD Soundsystem",
"Sly and the Family Stone",
"Daft Punk",
"Sonic Youth",
"Bjork",
"Roxy Music",
"Joni Mitchell",
"The Band",
"Simon and Garfunkel",
"Otis Redding",
"Sex Pistols",
"OutKast",
"Leonard Cohen",
"Ramones",
"The White Stripes",
"Ray Charles",
"The Jam",
"The Stooges",
"Fleetwood Mac",
"Wilco",
"Massive Attack",
"Al Green",
"The Police",
"Black Sabbath",
"ACDC",
"Elton John",
"Portishead",
"Frank Sinatra",
"Primal Scream",
"Patti Smith",
"Brian Eno",
"Queen",
"Kate Bush",
"Steely Dan",
"Duke Ellington",
"Blondie",
"Buddy Holly & The Crickets",
"Pavement",
"Arctic Monkeys",
"My Bloody Valentine",
"Eminem",
"Metallica",
"Sam Cooke",
"Pulp",
"FunkadelicParliament",
"The Strokes",
"Depeche Mode",
"The Flaming Lips",
"Guns n Roses",
"Pet Shop Boys",
"M.I.A.",
"Vampire Weekend",
"Nick Drake",
"Little Richard",
"Frank ZappaThe Mothers of Invention",
"Animal Collective",
"The Stone Roses",
"Randy Newman",
"Smashing Pumpkins",
"Coldplay",
"Charles Mingus",
"Aphex Twin",
"T. Rex",
"The Temptations",
"Peter Gabriel",
"Paul Simon",
"The Chemical Brothers",
"Pearl Jam",
"Captain Beefheart and His Magic Band",
"The National",
"Husker Du",
"The Jesus and Mary Chain",
"Run-D.M.C.",
"Eagles",
"Curtis Mayfield",
"Crosby Stills Nash (& Young)",
"Big Star",
"Elliott Smith",
"The Specials",
"Hank Williams",
"Missy Elliott",
"Roy Orbison",
"Grateful Dead",
"The Supremes",
"Cream",
"Rod Stewart",
"XTC",
"The Replacements",
"Weezer",
"Muddy Waters",
"Aerosmith",
"Smokey Robinson and The Miracles",
"The Everly Brothers",
"Spoon",
"Morrissey",
"Thelonious Monk",
"Serge Gainsbourg",
"Yeah Yeah Yeahs",
"Louis Armstrong",
"Belle and Sebastian",
"Red Hot Chili Peppers",
"Television",
"Queens of the Stone Age",
"Green Day",
"Dr. Dre",
"Janis JoplinBig Brother and The Holding Company",
"Nine Inch Nails",
"Sufjan Stevens",
"Deep Purple",
"Billie Holiday",
"A Tribe Called Quest",
"Bon Iver",
"The Streets",
"Can",
"Franz Ferdinand",
"Bo Diddley",
"Pretenders",
"De La Soul",
"Jefferson Airplane",
"TV on the Radio",
"Manic Street Preachers",
"Sigur Ros",
"Frank Ocean",
"Jeff Buckley",
"The Prodigy",
"Love",
"Dusty Springfield",
"Echo and the Bunnymen",
"Wire",
"Beyonce",
"Suede",
"Gorillaz",
"The Knife",
"Ornette Coleman",
"Air",
"Chic",
"Grizzly Bear",
"Justin Timberlake",
"The Verve",
"King Crimson",
"CaribouManitoba",
"The Libertines",
"Jerry Lee Lewis",
"ABBA",
"St. Vincent",
"John Cale",
"Phoenix",
"The Notorious B.I.G.",
"Modest Mouse",
"Iggy Pop",
"Deerhunter",
"Gang of Four",
"N.W.A",
"Fugazi",
"Interpol",
"Hot Chip",
"Herbie Hancock",
"The Drifters",
"DJ Shadow",
"Tom Petty",
"Scott Walker",
"Paul McCartney",
"Alice Cooper",
"MGMT",
"Carole King",
"Happy Mondays",
"Tim Buckley",
"Robert Wyatt",
"Lynyrd Skynyrd",
"Public Image Ltd.",
"The Allman Brothers Band",
"Dexys Midnight Runners",
"Santana",
"Eric B. & Rakim",
"Van Halen",
"The Ronettes",
"M83",
"Four Tops",
"Ella Fitzgerald",
"James Blake",
"Howlin Wolf",
"Buzzcocks",
"Derek and The Dominos",
"Wu-Tang Clan",
"Jackson Browne",
"Snoop Dogg",
"Yo La Tengo",
"Rage Against the Machine",
"Talk Talk",
"Robert Johnson",
"Suicide",
"Donna Summer",
"Fleet Foxes",
"Fats Domino",
"Foo Fighters",
"Nico",
"Robyn",
"Eric Clapton",
"Dire Straits",
"Sleater-Kinney",
"Janet Jackson",
"Motorhead",
"Gram Parsons",
"Dinosaur Jr.",
"The Fall",
"Ike and Tina Turner",
"Amy Winehouse",
"Buffalo Springfield",
"Flying Lotus",
"Sonny Rollins",
"Spiritualized",
"Burial",
"Underworld",
"Thin Lizzy",
"DAngelo",
"The Roots",
"Grandmaster Flash and The Furious Five",
"Soundgarden",
"Kendrick Lamar",
"Hole",
"The Pogues",
"The B-52s",
"Jonathan RichmanThe Modern Lovers",
"Todd Rundgren",
"The Isley Brothers",
"MC5",
"Genesis",
"Dizzee Rascal",
"Basement Jaxx",
"The Human League",
"Sinead OConnor",
"Traffic",
"Billy Bragg",
"Tricky",
"Yes",
"The Shins",
"Erykah Badu",
"Beach House",
"New York Dolls",
"Janes Addiction",
"Joanna Newsom",
"LL Cool J",
"Janelle Monae",
"The Animals",
"Drake",
"Fiona Apple",
"Cat Power",
"Bee Gees",
"Lucinda Williams",
"The XX",
"Violent Femmes",
"Boards of Canada",
"Dion",
"Devo",
"Small Faces",
"The Killers",
"The Jackson 5",
"Count Basie",
"Tame Impala",
"Stan Getz",
"George Harrison",
"Richard and Linda Thompson",
"Antony and The Johnsons",
"The War on Drugs",
"Bonnie Prince Billy",
"X",
"TLC",
"Isaac Hayes",
"Lauryn Hill",
"B.B. King",
"Fatboy Slim",
"Swans",
"ZZ Top",
"Disclosure",
"Mott the Hoople",
"The Righteous Brothers",
"Martha and The Vandellas",
"Prefab Sprout",
"Nas",
"The Zombies",
"Fairport Convention",
"Moby",
"George Michael",
"Supergrass",
"Nat King Cole",
"Pere Ubu",
"Eurythmics",
"Slayer",
"Willie Nelson",
"Fugees",
"Charlie Parker",
"2Pac",
"Super Furry Animals",
"Ian Dury",
"Dirty Projectors",
"Kiss",
"Kings of Leon",
"The Avalanches",
"FKA Twigs",
"The Black Keys",
"Procol Harum",
"The Breeders",
"Justice",
"Patsy Cline",
"Grimes",
"Frankie Goes to Hollywood",
"Ariel Pink",
"Little Feat",
"Duran Duran",
"Iron Maiden",
"Etta James",
"Siouxsie and The Banshees",
"Gnarls Barkley",
"The Rapture",
"The Crystals",
"Muse",
"The KLF",
"Jethro Tull",
"Madness",
"The Stranglers",
"The Shangri-Las",
"The Mamas and the Papas",
"Jackie Wilson",
"Liz Phair",
"Them",
"Stereolab",
"Neutral Milk Hotel",
"Mercury Rev",
"Eddie Cochran",
"Ben E. King",
"Dead Kennedys",
"The Go-Betweens",
"Bright Eyes",
"Bill Evans",
"The Flying Burrito Brothers",
"Orbital",
"Faith No More",
"Bing Crosby",
"The Monkees",
"Ry Cooder",
"Benny Goodman",
"The Undertones",
"Tori Amos",
"Cheap Trick",
"Ghostface Killah",
"Art Blakey",
"Run the Jewels",
"Godspeed You Black Emperor",
"Crowded House",
"Japandroids",
"The The",
"The New Pornographers",
"Guided by Voices",
"Cyndi Lauper",
"The Impressions",
"Wilson Pickett",
"Dolly Parton",
"Neu",
"Simple Minds",
"John Lee Hooker",
"Feist",
"Billy Joel",
"Teenage Fanclub",
"Lana Del Rey",
"The OJays",
"ABC",
"The La_s",
"Louis Jordan",
"Midnight Oil",
"The Shirelles",
"The Horrors",
"Kylie Minogue",
"James Taylor",
"Blue Oyster Cult",
"Glenn Miller",
"Magazine",
"Dizzy Gillespie",
"The Waterboys",
"Tears for Fears",
"Gene Vincent",
"Harry Nilsson",
"Bloc Party",
"Garbage",
"Bob Seger",
"Joao Gilberto",
"Yardbirds",
"Bill Haley and His Comets",
"The Orb",
"Elastica",
"Soft Cell",
"The Hold Steady",
"Adele",
"Elbow",
"Dr. John",
"Panda Bear",
"The Postal Service",
"Gil Scott-Heron",
"Built to Spill",
"Ryan Adams",
"The Cars",
"Joe Jackson",
"Bat for Lashes",
"Judy Garland",
"Cypress Hill",
"Black Flag",
"Sam and Dave",
"Tortoise",
"Rihanna",
"Todd Terje",
"The Damned",
"The Cramps",
"Soul II Soul",
"Eels",
"Bill Withers",
"The Gun Club",
"The Kingsmen",
"Boogie Down Productions",
"Jeff Beck",
"Bessie Smith",
"Nina Simone",
"Mary J. Blige",
"The Lovin Spoonful",
"Sparks",
"Future Islands",
"Neneh Cherry",
"Warren Zevon",
"Alanis Morissette",
"The Carter Family",
"Broken Social Scene",
"Grace Jones",
"Girls",
"Cat Stevens",
"Max Roach",
"Neko Case",
"Sun Kil Moon",
"System of a Down",
"Glen Campbell",
"Flamin Groovies",
"Big Black",
"Toots and The Maytals",
"Cloud Nothings",
"Dave Brubeck",
"Booker T. & The MGs",
"Gary Numan",
"Cocteau Twins",
"Rush",
"Kelis",
"Kurt Vile",
"Ice Cube",
"Afrika Bambaataa The Soulsonic Force",
"Big Boi",
"Squeeze",
"Woody Guthrie",
"Battles",
"Lily Allen",
"Aaliyah",
"Lee Perry The Upsetters",
"Minutemen",
"Real Estate",
"Leftfield",
"Donovan",
"The Soft Machine",
"Richard Hell & The Voidoids",
"tUnE-yArDs",
"The 13th Floor Elevators",
"The Cult",
"Sharon Van Etten",
"Joe Cocker",
"Jessie Ware",
"Def Leppard",
"Pharrell Williams",
"Wild Beasts",
"The Coasters",
"Dionne Warwick",
"The Platters",
"Jimmy Cliff",
"Boston",
"Mogwai",
"Big Joe Turner",
"Destroyer",
"Britney Spears",
"Manu Chao",
"Tracy Chapman",
"Carl Perkins",
"Sun Ra",
"Rufus Wainwright",
"Augustus Pablo",
"Metronomy",
"Steve Miller Band",
"Electric Light Orchestra",
"Slint",
"Steppenwolf",
"Royksopp",
"Faust",
"Bobby Bland",
"Graham Parker",
"Los Lobos",
"Alain Bashung",
"Tindersticks",
"Wayne Shorter",
"Laurie Anderson",
"Del Shannon",
"John Mellencamp",
"Solomon Burke",
"Fela Kuti",
"Clipse",
"X-Ray Spex",
"Bill Callahan",
"The Magnetic Fields",
"Carpenters",
"altJ",
"Haim",
"Lloyd Price",
"Perfume Genius",
"Lil Wayne",
"Nick Lowe",
"The Walkmen",
"Fred Astaire",
"Faces",
"Junior Boys",
"Mos Def",
"Cut Copy",
"The Lemonheads",
"Hercules and Love Affair",
"Burning Spear",
"Diana Ross",
"Spacemen 3",
"At the Drive-In",
"Four Tet",
"Free",
"Alicia Keys",
"Loretta Lynn",
"Spencer Davis Group",
"Marianne Faithfull",
"808 State",
"Destinys Child",
"Raekwon",
"Supertramp",
"Bad Brains",
"Lady Gaga",
"Tool",
"Goldie",
"Crystal Castles",
"Arrested Development",
"Saint Etienne",
"The Slits",
"Lloyd Cole and The Commotions",
"Mahavishnu Orchestra",
"The Afghan Whigs",
"Doves",
"Santigold",
"The Rascals",
"Lykke Li",
"Deee-Lite",
"Desmond Dekker",
"Beirut",
"Cornershop",
"The Sonics",
"Lenny Kravitz",
"Go-Gos",
"Grandaddy",
"Mike Oldfield",
"The Decemberists",
"George Jones",
"Laura Nyro",
"Mission of Burma",
"Albert Ayler",
"Frankie Lymon and The Teenagers",
"The Jon Spencer Blues Explosion",
"Bud Powell",
"Ministry",
"Meat Puppets",
"The Beat",
"Alice in Chains",
"My Morning Jacket",
"Weather Report",
"Dr. Feelgood",
"Orange Juice",
"Goldfrapp",
"Jack White",
"Eric Dolphy",
"Jimmie Rodgers",
"Bill Monroe",
"The Beta Band",
"INXS",
"Jacques Brel",
"Harold Melvin and The Blue Notes",
"Fuck Buttons",
"The Moody Blues",
"dEUS",
"Bonnie Raitt",
"The Pretty Things",
"Leadbelly",
"The Notwist",
"John Martyn",
"The Psychedelic Furs",
"Chromatics",
"The Dismemberment Plan",
"Fats Waller",
"Artie Shaw",
"Madvillain",
"Clifford Brown",
"Tina Turner",
"Liars",
"Whitney Houston",
"War",
"The Troggs",
"Emmylou Harris",
"Os Mutantes",
"Caetano Veloso",
"Ash",
"Les Rita Mitsouko",
"Blood Sweat & Tears",
"Antonio Carlos Jobim",
"Percy Sledge",
"The Saints",
"Adam and The Ants",
"Youssou NDour",
"The Offspring",
"Meat Loaf",
"Death Cab for Cutie",
"Badly Drawn Boy",
"Gang Starr",
"Chick Corea",
"Edith Piaf",
"Steve Earle",
"The Feelies",
"Bon Jovi",
"Sister Sledge",
"The Meters",
"The Black Crowes",
"Kyuss",
"Scritti Politti",
"Low",
"Keith Jarrett",
"Galaxie 500",
"Don McLean",
"Scissor Sisters",
"The Gossip",
"The Sugarcubes",
"Culture Club",
"Bobby Darin",
"Fever RayKarin Dreijer",
"Ritchie Valens",
"Rickie Lee Jones",
"Nancy Sinatra",
"Mazzy Star",
"The Hives",
"50 Cent",
"Syd Barrett",
"Suzanne Vega",
"John Mayall",
"The Only Ones",
"Okkervil River",
"Blumfeld",
"The Four Seasons",
"Paul Weller",
"Chris Isaak",
"The Sugarhill Gang",
"Lee Morgan",
"Cecil Taylor",
"Foals",
"Johnny Burnette",
"Placebo",
"Savages",
"Hawkwind",
"Sugar",
"10cc",
"Derrick May",
"Of Montreal",
"Ride",
"Moby Grape",
"Earth Wind & Fire",
"Bauhaus",
"Young Marble Giants",
"The Box Tops",
"Common",
"Donald Fagen",
"Buena Vista Social Club",
"The Shadows",
"Quicksilver Messenger Service",
"Noir Desir",
"The Pop Group",
"Lorde",
"The Orioles",
"The Boo Radleys",
"Lambchop",
"Brian Wilson",
"Daryl Hall and John Oates",
"The Jayhawks",
"Wolf Parade",
"Japan",
"R. Kelly",
"Mano Negra",
"Drive-By Truckers",
"Roni SizeReprazent",
"The Walker Brothers",
"Mahalia Jackson",
"Spinners",
"Sarah Vaughan",
"Iron & Wine",
"Mastodon",
"Band of Horses",
"Jungle Brothers",
"Usher",
"The Weeknd",
"The Modern Jazz Quartet",
"Throbbing Gristle",
"King Sunny Ade",
"Gladys Knight and The Pips",
"Oliver Nelson",
"Slade",
"Blind Faith",
"The Charlatans",
"Peter Bjorn and John",
"Travis",
"Gillian Welch",
"Klaxons",
"John Hiatt",
"Everything But the Girl",
"Link Wray",
"Albert King",
"John Prine",
"Wes Montgomery",
"Chic Chic Chic",
"k.d. Lang",
"Miguel",
"Nicki Minaj",
"Sepultura",
"Grinderman",
"Chvrches",
"Question Mark and the Mysterians",
"Marilyn Manson",
"Shabazz Palaces",
"Cliff Richard",
"Salt n Pepa",
"J.J. Cale",
"Peter Tosh",
"Fucked Up",
"Angel Olsen",
"The Birthday Party",
"The Sundays",
"Yeasayer",
"Julia Holter",
"Mink DeVille",
"Living Colour",
"The Microphones",
"Dinah Washington",
"Horace Silver",
"The Associates",
"A Guy Called Gerald",
"Gang Gang Dance",
"Calexico",
"The Neville Brothers",
"Inner City",
"The Congos",
"Stiff Little Fingers",
"Deafheaven",
"Ol Dirty Bastard",
"Andy Stott",
"Donny Hathaway",
"The Raconteurs",
"Jorge Ben",
"The Pharcyde",
"Korn",
"Ann Peebles",
"Salif Keita",
"Sleigh Bells",
"Screamin Jay Hawkins",
"Emerson Lake & Palmer",
"Camera Obscura",
"Minor Threat",
"Labelle",
"Henry Mancini",
"Stereo MCs",
"The Dandy Warhols",
"Little Willie John",
"Tammy Wynette",
"J Dilla",
"Jackie Brenston",
"The Blue Nile",
"The Coral",
"Annie",
"The Teardrop Explodes",
"The Staple Singers",
"Townes Van Zandt",
"No Doubt",
"The Antlers",
"The House of Love",
"Sade",
"Einsturzende Neubauten",
"En Vogue",
"Fred Neil",
"Michel Polnareff",
"Phil Spector",
"The Cranberries",
"The Chiffons",
"The Incredible String Band",
"Nancy Sinatra Lee Hazlewood",
"Linda Ronstadt",
"Sting",
"Iron Butterfly",
"The Residents",
"Coleman Hawkins",
"Mobb Deep",
"Rick Nelson",
"Gloria Gaynor",
"Cannonball Adderley",
"The Paul Butterfield Blues Band",
"Culture",
"James Carr",
"Aztec Camera",
"Charles Trenet",
"This Mortal Coil",
"Phil Collins",
"LFO",
"Rick James",
"Judas Priest",
"Stardust",
"Tim Hardin",
"The Doobie Brothers",
"MARRS",
"Autechre",
"Death Grips",
"Phosphorescent",
"Tocotronic",
"The Heartbreakers",
"David Sylvian",
"The Flamingos",
"Chet Baker",
"Sparklehorse",
"Tommy James and The Shondells",
"Tom Tom Club",
"Ruben Blades",
"T.I.",
"Chubby Checker",
"Mac DeMarco",
"Terry Riley",
"Heaven 17",
"David Byrne",
"The Five Satins",
"Jens Lekman",
"Roberta Flack",
"Oneohtrix Point Never",
"George Russell",
"Taylor Swift",
"Stevie Ray Vaughan",
"Country Joe & The Fish",
"Naughty by Nature",
"These New Puritans",
"Peter Frampton",
"Blink-182",
"Al Jolson",
"They Might Be Giants",
"Fingers Inc.",
"John Zorn",
"The Sisters of Mercy",
"Cameo",
"Freda Payne",
"Cabaret Voltaire",
"Mekons",
"Ali Farka Toure",
"Joan Jett and The Blackhearts",
"Stray Cats",
"Joan Baez",
"Fennesz",
"Yoko Ono",
"Boz Scaggs",
"No Age",
"Method Man",
"Willie Mae Big Mama Thornton",
"The Wedding Present",
"Gordon Lightfoot",
"Average White Band",
"Digital Underground",
"Nusrat Fateh Ali Khan",
"Elmore James",
"The Dream Syndicate",
"Tyler The Creator",
"Gene Autry",
"John Fogerty",
"Art Ensemble of Chicago",
"Gil Evans",
"Jimmy Giuffre",
"Midlake",
"Sebadoh",
"Robert Plant",
"Blind Lemon Jefferson",
"El-P",
"Killing Joke",
"Blind Willie Johnson",
"Bix Beiderbecke",
"Jerry Butler",
"Chicago",
"Killer Mike",
"AlunaGeorge",
"Merle Haggard",
"Spirit",
"Tangerine Dream",
"The Andrews Sisters",
"Ozzy Osbourne",
"Glasvegas",
"Parquet Courts",
"Steve Reich",
"EPMD",
"Bob Wills and His Texas Playboys",
"The Cardigans",
"Mudhoney",
"Busta Rhymes",
"N.E.R.D.",
"Stephen Stills",
"Fine Young Cannibals",
"Marty Robbins",
"The Wrens II",
"Phil Ochs",
"Ricardo Villalobos",
"Roy Acuff",
"LaVern Baker",
"L7",
"David Crosby",
"Moloko",
"Bangles",
"Damien Rice",
"Devendra Banhart",
"Sarah McLachlan",
"Cab Calloway",
"Yazoo",
"Bad Company",
"Dexter Gordon",
"Sheryl Crow",
"The Nitty Gritty Dirt Band",
"The Mars Volta",
"Jimmy Reed",
"Gwen Stefani",
"GZAGenius",
"Van Dyke Parks",
"Don Henley",
"Canned Heat",
"Melle Mel",
"Tim Hecker",
"Bryan Ferry",
"Le Tigre",
"Anita Baker",
"Richard Hawley"]
